<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AngleSharp" Version="1.2.0"/>
        <PackageReference Include="Fizzler.Systems.HtmlAgilityPack" Version="1.2.1"/>
        <PackageReference Include="HtmlAgilityPack" Version="1.11.72"/>
        <PackageReference Include="PuppeteerSharp" Version="20.1.0"/>
        <PackageReference Include="VIEApps.Components.Utility.Epub" Version="10.9.2501.2"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="scraps\"/>
    </ItemGroup>

</Project>
